### ISSUE TITLE
"What kind of track?" test is not working

### ISSUE THREAD

**Issue by HugoGiraudel** [ffoodd/a11y.css#111]
[This test](http://ffoodd.github.io/a11y.css/advices.html#track): hovering the player does nothing.

Chrome Version 38.0.2125.122 Mac OS X Yosemite.

**Comment by ffoodd** [comment]
From [the spec](http://www.w3.org/TR/html-markup/track.html) track is a void tag, but I already added the $self-closing parameter.

Trying to display this message, I couldn't. Even with display: block and dimensions, this did nothing. It makes sense while it won't be displayed.

I will probably remove this test-case since it won't work :(
