### ISSUE TITLE
img[alt] tests conflict each others

### ISSUE THREAD

**Issue by HugoGiraudel** [ffoodd/a11y.css#112]
[This error](http://ffoodd.github.io/a11y.css/errors.html#no-alt) and [this warning](http://ffoodd.github.io/a11y.css/warnings.html#empty-alt) conflict each others. Don't they?

**Comment by ffoodd** [comment]
Not at all, they are both needed:
* alt must be present, even if empty - otherwise we get an error;
* alt should be pertinent, so if empty we get a warning.

An empty alternative is a good thing if the picture doesn't carry any information. It reflects the lack of information. There's still a need for a warning since a picture that doesn't serve the content should probably better be added as a background-image with CSS, but that's arguable.

Did I miss anything else?
