### ISSUE TITLE
Issue with alt and figcaption

### ISSUE THREAD

**Issue by HugoGiraudel** [ffoodd/a11y.css#120]
When using and `img` as part of a `figure` containing a `figcaption`, the `alt` attribute should be left empty (as stated in I don't know what document).

Although a11y.css seems to choke on this.

**Comment by a5e** [comment]
W3C working draft is saying the opposite [here](http://www.w3.org/TR/html-alt-techniques/#m6):

> Until the figure and figcaption elements are widely accessibility supported by browsers and/or assistive technology it is recommended that role="group" be used on the figure element and in the case where the figcaption content is the text alternative, provide a label for the image in the alt attribute.

**Comment by ffoodd** [comment]
Indeed, and this makes sense after reading the working draft: figcaption is meant to label everything inside a figure, not only image. In some cases, alt would label the picture and figcaption the group of content inside a figure.

So I guess that's a won't fix.

**Comment by a5e** [comment]
But maybe we could add a test for this recommendation ?

> ... it is recommended that role="group" be used on the figure element ...

**Comment by ffoodd** [comment]
It used to be one, but I removed it for some reason. Can't remember why :/
I open another issue to add that case back.

**Comment by sunnywalker** [comment]
I'd like to revisit this issue now in 2019. Is the recommendation still that all `<figure>` tags have the role of `group`?

[This HTML spec](https://www.w3.org/TR/html52/grouping-content.html#the-figure-element) says that `<figure>` can have the `figure` (do-not-set), `group`, and `presentation` roles. And for the [figure role](https://www.w3.org/TR/wai-aria-1.1/#figure):

> Authors MAY reference text serving as a caption using aria-describedby. Authors MAY provide a label using aria-label or MAY reference text serving as a label using aria-labelledby.

So is it still a non-spec recommendation that all figures are `group` roles, even when they only contain one image because of poor support by AT vendors (even 4 years later)?

**Comment by ffoodd** [comment]
Thanks @sunnywalker for questionning this :)

The point is: does expliciting `role` on `figure` — as well as on `nav`, `header` et all — still needed to improve AT support?

Expliciting roles isn't a spec requirement, neither an error (since it only triggers a warning in the Validator, being syntactically correct), but a user experience improvement.

I'll make some reasearch about implicit roles support by ATs, to know whether those `role` are still needed or not.
