### ISSUE TITLE
figure needs role="group"

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/a11y.css#121]
As said in #120 and as far as we know (from the W3C's WD) figure needs a role="group" for accessibility reasons.

I think this should be a warning. Any thought?

**Comment by Lamecarlate** [comment]
Hiya! Is this warning still relevant today? The associated links in wiki (http://references.modernisation.gouv.fr/rgaa/criteres.html#crit-1-10, http://www.w3.org/WAI/tutorials/images/decision-tree/, http://www.w3.org/TR/html51/semantics.html#alt) seem to relate to the "alt" attribute and not the "figure" element, and in the issue #120 the link to WD is now dead. I can't find any recommendation about a role on "figure" element…

**Comment by ffoodd** [comment]
Hi there :) thanks for questioning!

In fact it is still needed, as seen in every tests for 1-10 criteria in RGAA v3 (the first link). Each five tests requires a `<figure role="group">`  parent.

And the WAI tutorial ("The alt decision tree") also uses `<figure role="group">` for last cases: complex images and groups of images. In both case, the use of a `<figure>` element goes along a `group` role.

As far as I know, it's all a matter of progressive enhancement for assistive technologies: some might support roles but not tags, and the other way too…

The most recent resource I found about this is [a comment on a dedicated topic of Atalan's AcceDeWeb notice (in french)](http://www.accede-web.com/notices/html-css-javascript/6-images-icones/6-4-images-legendees-figure-rolegroup-figcaption/#comment-258). For now it does not really help, but we can't know if some assistive tech nonsupporting role or figure will not start to support one.

So while a single combo of popular At + browser still not supports the semantic of figure and figcaption, we should be adding a group role on figure.

**Comment by Lamecarlate** [comment]
OK, I totally misread the RGAA page, sorry.

Thanks for your answer! I have now good arguments to support my future pull request on https://github.com/OleVik/grav-plugin-imgcaptions :D

**Comment by ffoodd** [comment]
A pleasure to read, check, update and help to help :) 
Keep going!

**Comment by sebastiangreger** [comment]
Hi. I greatly value a11y.css as a tool for quick assessment, but this warning about `role="group"` throws me off every time...

There is an [open ticket on the referenced WAI Tutorial repo](https://github.com/w3c/wai-tutorials/issues/604) indicating that, as of 2017, ARIA 1.1 provides `role="figure"`. Since this is the implicit ARIA role of the `<figure>` tag, shouldn't this be the correct role to assign, rather than overriding it with `group`? An investigation by Scott O'Hara and his markup recommendation seem to support that as well: https://www.scottohara.me/blog/2019/01/21/how-do-you-figure.html
