### ISSUE TITLE
Design a logo + styleguide for the project

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/a11y.css#163]
Could be useful To themify Hologram + Sassdoc and to enhance the incoming twitter account.

**Comment by ffoodd** [comment]
First drafts for logo, any thoughts? I'm having fun but I'm not so good at designing a logo…
![draft-1](https://cloud.githubusercontent.com/assets/2890570/12234243/d4c820aa-b86b-11e5-93b2-88810cc2ca16.png)
![draft-2](https://cloud.githubusercontent.com/assets/2890570/12234242/d4c5f596-b86b-11e5-8847-17d16094c2fc.png)

**Comment by christophermh44** [comment]
Prefered one: the red filled square :)

**Comment by Heydon** [comment]
I like the red triangular one!

**Comment by kaishin** [comment]
Hi, I got sent here by @HugoGiraudel from twitter.

I like that this is being tackled in the open. Props!

I would probably leave color for later initially, since it will make it hard to look at the shapes and their qualities and flaws.

Color aside, the triangular shapes were a bit hard for me to understand, especially the filled ones where the triangle is cut off at the top. The rounded square (filled) looks more solid.

For the comic style eyes, I am not too sure about how obvious they are. Did you try something symmetrical? It could be worth it to experiment with reducing details and cleaning up the lines to make the logo more recognizable.

Overall good start!

**Comment by ffoodd** [comment]
Thanks everyone! Almost every advices are going to the red filled tries, so it'll probably be that kind of style.

@kaishin I'll try to make it cleaner and to work without colors. For now there's only @Heydon who preferred the triangle (sorry dude :D), so I'll go with rounded square. I didn't try symmetrical, I will.

The idea was to get a strong character; but I probably went too fast to the drawing :)

If you (anyone) have an idea or a recommendation, please comment :)

**Comment by JulienGremillot** [comment]
I'm joining the supporters of the red filled square !

**Comment by ffoodd** [comment]
New try, symmetrical things, straight font and in black to start:
![capture d ecran 2016-01-11 a 17 19 14](https://cloud.githubusercontent.com/assets/2890570/12239129/8ce584fa-b887-11e5-8c1b-0532f488b222.png)

Two fonts tried, Fira Sans and Chalkboard. Very funny to see how much a font gives a personality to an emoji like this :)

**Comment by kaishin** [comment]
I think ideally the ultimate decision should be up to @ffoodd ;) Open design != Design by committee.

The rounded square with round line caps looks very clean! It'd be nice to try some colors on it and see which one make most sense of the project. Since it's about warnings yellow/orange/red are all good candidates.

It's probably worth trying the symmetry/line caps with a triangle as well. Just to give some context on how the design evolved.

**Comment by ffoodd** [comment]
A few more tries. The last four on bottom right are using a11y.css' messages' theme. I'm not satisfied from those tests, I'll keep going :)

Any thought welcome, as usual—and thanks @kaishin  for your advices ;)

![a11y-0](https://cloud.githubusercontent.com/assets/2890570/12267081/a66b7a78-b946-11e5-9f7b-6f6f5ccfa23c.png)

**Comment by ffoodd** [comment]
I do prefer those two:
![a11y 2](https://cloud.githubusercontent.com/assets/2890570/12267875/802771ba-b94a-11e5-91b2-b4f3750600c8.png)

**Comment by GaetanBt** [comment]
And what about those two and the last two from your previous message with the non-symmetrical thing ?

**Comment by kaishin** [comment]
@ffoodd Nice choice! I liked the filled ones in general, especially those with lower contrast like the yellow one.

**Comment by kaishin** [comment]
By liked I mean, they look less urgent.

**Comment by ffoodd** [comment]
Indeed, already heard that both red color(s) and borders are way too stressful. 

I think yellow or orange filled square, without borders, are for now the best choices. Green or blue ones seems conflicting the idea of warning and test.

**Comment by ffoodd** [comment]
Today's tries:
![a11y 3](https://cloud.githubusercontent.com/assets/2890570/12299726/66a685cc-ba18-11e5-8c90-0ae2374f7e64.png)

Nothing sure, just exploring emojis styles.

**Comment by ffoodd** [comment]
I'm going with this:
![a11y-css](https://cloud.githubusercontent.com/assets/2890570/12424776/db6eac96-bed1-11e5-9598-02454b772146.png)

I'll need to explore a few color schemes before using it, but it begins to look good.
As usual, comments are welcome :)

**Comment by ffoodd** [comment]
May try some secondary colors:
* http://paletton.com/#uid=31m0u0kw0w0jvDaoOy4y4oODajv
* https://color.adobe.com/fr/create/color-wheel/?base=2&rule=Compound&selected=3&name=Mon%20th%C3%A8me%20Color&mode=rgb&rgbvalues=0.7764399452809085,0.8,0.07999999999999999,0.5882199726404542,0.6,0.24,1,0.807843137254902,0,0.25,0.4683281733749709,1,0.07999999999999999,0.4790687306506879,0.8&swatchOrder=0,1,2,3,4

Still working :)

**Comment by ffoodd** [comment]
SVG file :)
[a11y.svg.zip](https://github.com/ffoodd/a11y.css/files/132033/a11y.svg.zip)

**Comment by ffoodd** [comment]
No need for a styleguide, and logo's done :)
