### ISSUE TITLE
Add a rule : no form in a form

### ISSUE THREAD

**Issue by vibby** [ffoodd/a11y.css#295]
I met this error and would have love a11i.css to tell it to me :)
You could add this check to a11i.css : throw error when finding the selector «form form»

References :
XHTML : https://www.w3.org/TR/xhtml1/#prohibitions
HTML5 : http://w3c.github.io/html/sec-forms.html#the-form-element

**Comment by ffoodd** [comment]
Hi there!

Indeed, that's a good idea for a new test :) Pretty rare case hopefully!

Stay tuned, I'll add it soon ;) Thanks!

**Comment by ffoodd** [comment]
And here it is, [nested interactive elements test](http://ffoodd.github.io/a11y.css/errors.html#nested-interactive).

In fact it's going further, since nesting any interactive tags is forbidden per the spec.

And FYI, `form form` is quite useless since browsers (or at least, Firefox) already remove the unwanted `<form>`. I guess other browsers act the same, however I didn't test it! 

Thanks for your suggestion, it made me read the specification again ;)
