### ISSUE TITLE
`require()` in sass file

### ISSUE THREAD

**Issue by chrisopedia** [ffoodd/a11y.css#297]
Am I doing something wrong?  There is a `require` statement in the sass files preventing me from including it in my sass project.

**Comment by ffoodd** [comment]
No I think you're good!

Just to be sure, you're trying to include Sass sources in your projects, to compile it by yourself?

If so, the `require` (coming from `sassport`, in [gulp-sassport](https://www.npmjs.com/package/gulp-sassport)) is used to get the `.json` file for messages in the main files, thus should be a project dependency.

It's currently a dev dependency, and moreover a Gulp plugin: it should also be tool agnostic, to allow you to use Grunt, Webpack or whatever to compile. I'll try to improve it ASAP.

**Comment by ffoodd** [comment]
In fact this won't be as simple as I thought, since `sassport` is more a `node-sass` wrapper than a dependency. Working on it!

@HugoGiraudel if possible, I'd love to have your thought :)

**Comment by ffoodd** [comment]
Maybe a `prepare` script could help?

**Comment by chrisopedia** [comment]
Do the messages have to be in `.json`?  Can you put them in a Sass map?

**Comment by HugoGiraudel** [comment]
Hello. 

a11y.css has never been intended to be included in one’s project, so we were not too worried about the use of sassport. 

From there, we have several ways to proceed. The easy solution although sub-optimal, is to make sassport a mandatory dependency of a11y.css. Not ideal.

Otherwise, we would need to move the translations back into a Sass map, which is also not ideal because Sass maps is not your typical ideal data format, but that would save us from using Sassport entirely.

**Comment by ffoodd** [comment]
I think the extra-step is the way to go: 
- JSON is actually helpful, a11y.css is available in 5 languages thanks to its ease of use;
- adding a dependency seems weird since a11y.css is meant to be a single CSS file.

I understand the need for the ability to include its compilation in one's project to customize it, so pre-compiling translations to Sass files seems good.

I'll work on it soon :)

Thanks @HugoGiraudel for helping!

**Comment by ffoodd** [comment]
Hi there, 

this has been packed in 4.3.0 and should work :)

as a sidenote, I'm not using `json-sass` as it's faily unmaintained and caused me trouble with unquoted strings; I'm using a more advanced fork named [`rootbeer`](https://github.com/gkatsev/rootbeer).

**Comment by chrisopedia** [comment]
Thanks guys this is awesome.  Really appreciate it.
