### ISSUE TITLE
Error count not reliable

### ISSUE THREAD

**Issue by danygit** [ffoodd/a11y.css#309]
I just tested the firefox extension and the extension notice that i have 3 errors but i see only 2 error.

**Comment by ffoodd** [comment]
Tested on [orange.com](https://www.orange.com) :)

**Comment by ffoodd** [comment]
Got it! In fact this is not really a bug but a limitation.

Looking at the HTML source, an `<iframe>` triggers two tests: an error and a warning. And since it's hidden (with inline styles, matching the warning), no message can be displayed.

Welcome in a pure CSS world :) since there's nothing I can do for this, I just close the issue.
