### ISSUE TITLE
Error count varies

### ISSUE THREAD

**Issue by notabene** [ffoodd/a11y.css#310]
Depending on the CSS called, results in error count vary:

* a11y-en_error.css:
  * **Errors: 98**
* a11y-en_warning.css:
  * **Errors: 96**
  * Warnings: 95
* a11y-en_obsolete.css:
  * **Errors: 96**
  * Warnings: 95
  * Obsoletes: 1
* a11y-en_all.css:
  * **Errors: 94**
  * Warnings: 95
  * Obsoletes: 1
  * Advices: 62

All on the same page [undisclosed test URL].

**Comment by ffoodd** [comment]
I just test this, and as for #309 there's not much I can do: tags triggering multiple messages can't increment multiple counters, since`counter-increment` property is cascading. A single message is incrementing its counter (either selector is more specific or it is the last one), explaining why erros counter is higher when less levels are shown.

Using CSS only won't help for this one :/

**Comment by notabene** [comment]
Duly noted for webextension V2
