### ISSUE TITLE
Possible danger: Using rawgit.com as CDN is not recommended

### ISSUE THREAD

**Issue by jakubboucek** [ffoodd/a11y.css#333]
See https://github.com/rgrove/rawgit/blob/master/FAQ.md#what-should-i-use-rawgit-for

Next reason is high possible risky to current owner of project will leave the project, domain will expire and somebody another will register it - it can endanger users of your tool.

**Comment by ffoodd** [comment]
Hi! 

Thanks a lot for opening this issue! Indeed I used rawgit as a starting point but never moved on :/

Using another CDN or URL on the bookmarklet generator will be easy, however there's no way to update existing installed bookmarklets in users browsers. I'll search a way!

**Comment by jakubboucek** [comment]
I mean existing installed bookmarklets is unable to upgrade. That's by design. Unfortunately.

**Comment by danielweck** [comment]
https://rawgit.com
> RawGit has reached the end of its useful life

RawGit URLs can easily be converted to the JSDelivr URL format:
https://www.jsdelivr.com/rawgit
...but unfortunately it is now impossible to reference branch names such as `master` (only release tags are supported).

For example:
https://rawgit.com/ffoodd/a11y.css/master/css/a11y-en.css
...becomes an explicit Git revision / commit hash:
https://cdn.jsdelivr.net/gh/ffoodd/a11y.css@eb219e6909be7a67f80345c9bfe53fea83e6005c/css/a11y-en.css
(the rationale behind this design choice is cache optimizations, as explained here: https://github.com/jsdelivr/jsdelivr/issues/18101 )

Thankfully, the `latest` keyword can be used instead, in order to track the most recent stable build:
https://cdn.jsdelivr.net/gh/ffoodd/a11y.css@latest/css/a11y-en.css
...alternatively, the `latest` keyword is optional:
https://cdn.jsdelivr.net/gh/ffoodd/a11y.css/css/a11y-en.css
(note that this works fine right now, but this requires continued maintenance of *release tags* for the `a11y.css` project)

**Comment by danielweck** [comment]
Other viable alternatives to RawGit:
https://www.staticaly.com/rawgit
https://raw.githack.com
https://gitcdn.link
?

**Comment by ffoodd** [comment]
I didn't know about all these alternatives, thanks :)
I'll switch to jsdeliver for now, I guess (as soon as I can work on this again).

**Comment by danielweck** [comment]
A more future-proof option would be to copy the `a11y.css` file(s) to your `gh-pages` branch:
https://github.com/ffoodd/a11y.css/tree/gh-pages
This way, you will be able to serve the CSS files using the GitHub Pages URL format:
https://ffoodd.github.io/a11y.css/a11y-en.css

**Comment by danielweck** [comment]
Related issue: https://github.com/ffoodd/Talks/issues/4

**Comment by danielweck** [comment]
Mhmm, the "Generate the bookmarklet" button on this page:
https://ffoodd.github.io/a11y.css/

...still uses the RawGit URL (I cleared the web browser cache to make sure this wasn't an old script):
`https://rawgit.com/ffoodd/a11y.css/master/css/a11y-en.css`

```javascript
javascript:(function(){a11ycss=document.createElement("LINK");a11ycss.href="https://rawgit.com/ffoodd/a11y.css/master/css/a11y-en.css";a11ycss.rel="stylesheet";a11ycss.media="(min-width: 800px)";document.body.appendChild(a11ycss);})();
```

The default URL (without pressing the "generate" button) is correct:

`https://ffoodd.github.io/a11y.css/css/a11y-en.css`

```javascript
javascript:(function(){a11ycss=document.createElement('LINK');a11ycss.href='https://ffoodd.github.io/a11y.css/css/a11y-en.css';a11ycss.rel='stylesheet';a11ycss.media='all';document.body.appendChild(a11ycss);})();
```
