### ISSUE TITLE
to role=presentation or not

### ISSUE THREAD

**Issue by sunnywalker** [ffoodd/a11y.css#338]
There seems to be a conflict recommendation on `role="presentation"`.

https://github.com/ffoodd/a11y.css/blob/eb219e6909be7a67f80345c9bfe53fea83e6005c/sass/themes/_error.scss#L191
and
https://github.com/ffoodd/a11y.css/blob/eb219e6909be7a67f80345c9bfe53fea83e6005c/sass/themes/_warning.scss#L775

Which brings up a question. If `role="presentation"` is not widely supported yet, is it still bad? And is the statement still true in 2019 when [WAI-ARIA Practices 1.1](https://www.w3.org/TR/wai-aria-practices-1.1/#presentation_role) recommends using it? [This, admittedly older, article](http://john.foliot.ca/html5/aria-hidden/) suggests using **both** `role="presentation"` and `aria-hidden="true"` to cover all bases. How does using both properties together have a negative impact?

It seems like progressive enhancement would be recommended rather than warned against, but I may not have a full picture or may be misunderstanding the difference between `role="presentation"` and `aria-hidden="true"`.

Edit: I think most of my confusion stems from the differences between _specifications_ and _real world implementations_ and how different browsers (and AT) implement standards differently and possibly "not to spec" over the years. I appreciate that comparisons need to be made against some list of rules and the specs are the best option, but if they do not match the reality of deployed systems, are they good tests? I'm genuinely confused by the various and sometimes (seemingly) conflicting recommendations.

**Comment by ffoodd** [comment]
Hi there,

First things first, thank you for having read and searched that much before opening an issue, I greatly appreciate :)

You guessed it right,there're *lots* of differences between official recommendations and real world support. WAI-ARIA is a specification, as well as CSS, HTML or ECMASCRIPT. Browser and AT support is unequal.

That's why Section 508 or RGAA exists: they're some kind of real world interface for WCAG, and targets a defined range of browsers and ATs. But this is an infinite discussion: who do you work for, spec and tools, or end user? Getting errors or warnings in automated tools is sometimes a good thnig for the end user (eg: redundant ARIA roles matching implicit role for the element). But this is  a wider discussion and you'll find tons of different approaches, perspectives and people to think with.

For the current example, please consider the whole CSS selector for each case: 
1. the first one targets SVG element with a `img` role: if they have this role, they obviously should have an alternative text (using `aria-label` for example). If they don't, they shouldn't be treated as graphics, and therefore should be hidden  from the accessibility tree using either `aria-hidden` or `role=presentation` (or both? :D ).
2. then the warning only says that if you used `role=presentation` only, that won't be enough and should be  used alongwith `aria-hidden`.

They are actually complementary, one of them dealing with SVG being unlabelled `img` (and that's an error), the otherone  with SVG (and other image elements) being decorative but uncorrectly hidden from the accessibility tree (a warning).

As per the spec, you should ensure you use `role=presentation` for decorative SVG, that's why the error documentation explains this. But for the end user care, ou also should use `aria-hidden`, and that's where the warning appears.

What if the error already talked about `aria-hidden` on decorative SVG? Well, you wouldn't have notice it, nor learned that it also applies to other image elements.

I hope it helps, and please tell me I you think I did something wrong: I want to keep improving a11y.css :)

Thanks again.

**Comment by sunnywalker** [comment]
Thank you very much for this explanation and clarification. I now see how the two tests are complimentary.

After posting this issue, I also came across this article [describing the difference between role=presentation and aria-hidden=true](https://timwright.org/blog/2016/11/19/difference-rolepresentation-aria-hiddentrue/) which helped explain, in the best case of universal implementation of specs, how each should be used.

I'm still torn between using both parameters because some of my work requires WCAG 2 A, AA compliance but the metric used for testing is based on automated tools; such tools don't appreciate the difference between the specs and real world implementations.

The "correct" answer for a11y is to use both properties; the "best" answer, when dealing with compliance issues, is to use only one.
