### ISSUE TITLE
Use `[*=" "]` to check for forbidden whitespaces

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/a11y.css#397]
A few attributes shouldn't contain any whitespace, such as `id` or `lang` (see #396).

@matuzo's clever selector using the **contains** flag for attribute selector would help a lot. Things to consider:
- [x] Which HTML attributes shouldn't contain whitespace?
- [x] Which current tests could be improved this way?
- [x] Which of whitespaces should be tested? Tricky trick gone too far, maybe? 

Quite a big one :)

**Comment by ffoodd** [comment]
Other way around: should it have its own test, just as invalid nesting? This is syntax, after all.
Or improving current attributes selctors would cover the same?

**Comment by matuzo** [comment]
For the sake of completeness, it was @Schepp's idea. I just made the demos and tested it. :)

**Comment by ffoodd** [comment]
Thanks for pointing him out :+1: 
Everyone will go to the credits page, wouldn't have discover it without your sharing :D

**Comment by Dionakra** [comment]
Reading the HTML standard, I only found two attributes that may not include whitespaces:
* [[id]](https://html.spec.whatwg.org/#the-id-attribute): _The id attribute value must be unique amongst all the IDs in the element's tree and **must contain at least one character. The value must not contain any ASCII whitespace**._
* [map[name]](https://html.spec.whatwg.org/#the-map-element): _The name attribute gives the map a name so that it can be referenced. **The attribute must be present and must have a non-empty value with no ASCII whitespace**_

Regarding the `lang` tag, there is not [anything specific about whitespaces](https://html.spec.whatwg.org/#attr-lang). I will write what I found in #396.

**Comment by ffoodd** [comment]
Well, in fact [the RFC mentions that no whitespace should be present in a language tag (2 paragraphs above this anchor)](https://tools.ietf.org/html/bcp47#section-2.1.1) and the spec says "Its value must be a valid BCP 47 language tag" — using "a", so I interpret this as "a single".

As far as I understand, that means `lang` attribute should not contain whitespace either—am I missing something?

**Comment by Dionakra** [comment]
You are correct, I didn't read that RFC in detail, this I missed that part. Sorry about that! Will include that check in the #396 as well.

**Comment by ffoodd** [comment]
No worry, reading specs and RFCs is not a that easy (and probably not everyone's hobby neither!). Your insights and researches is greatly appreciated, thanks a lot :heart:
