### ISSUE TITLE
`<select required>` should start with an empty value `option`

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/a11y.css#404]
Sources:
— https://twitter.com/WebPlatformNews/status/1346492730223058946
— https://html.spec.whatwg.org/multipage/form-elements.html#placeholder-label-option
— https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fjsbin.com%2Ftozopid%2Fquiet

First idea:

```css
select[required]:not([multiple]) option:first-child:not([value=""]):not([value=" "]) {
  …
}
```

**Comment by Dionakra** [comment]
Hi, 

I am trying to add this check to the library, but I am having a problem regarding showing the actual error message. Based on the first idea, I came up to this:

```css
option:first-child:not([value=""]):not([value=" "]) {
  select[required]:not([multiple])[size="1"] &,
  select[required]:not([multiple]):not([size]) & {
    @include error('select-option-not-empty', $self-closing: true);
  }
}
```

But there are few caveats regarding the `<select>` tag and this CSS selector:
* The selector is getting the `<option>` node, not the parent `<select>` node, so whatever we are applying here, it would be done to the first `<option>` element.
* With `$self-closing: false`, the message is appended to the option between two `<option>` tags, hence not showing itself.
* With `$self-closing: true`, the message will is prepended to the next found node, which is another `<option>` tag, hence not showing itself.
* Even if there were only one `<option>` tag, the `::before` and `::after` pseudo-classes don't work with the `<select>` tag, as `<select>` tags [are generated by the OS](https://stackoverflow.com/a/3533807), so putting a `::before` or an `::after` pseudo-class wouldn't show the error.
* With the previous point, it would work only if, instead of selecting the `<option>` node, we were selecting the `<select>` node. It seems that this could be done using the [`:has()`](https://developer.mozilla.org/en-US/docs/Web/CSS/:has) pseudo-class, but it is still not standardized as it belongs to _CSS Selectors Level 4 specification_.


I also tried to get to the parent `<select>` node for the selected `<option>` node by using the `@at-root` keyword, but it wouldn't ensure anything.

Do you have any clue on how to keep working on this? 

In the meantime I will change my focus to another issue :smile:

**Comment by ffoodd** [comment]
Hi @Dionakra, thanks for trying this out!

Indeed `<select>` is a replaced element, so it can't hold any pseudo-element—I mentionned it in a11y.css wiki's ["Edge cases and known issues"](https://github.com/ffoodd/a11y.css/wiki/Edge-cases-and-known-issues) but completely forgot about this when opening this PR.

To sum up:
- we cannot display a pseudo-element in both `select` and `option`;
- we may use `$self-closing` and target `select` to display message in a sibling element;
- while targetting `select` we can't know if the first `option` has an empty `value`: `:has()` is not supported anywhere ATM.

Considering this, I suggest:
1. this **test should be an advice** since we will only target `select[required]:not([multiple])` and advice to check its first `option`'s value manually,
2. obviously use `$self-closing` to maximize our chances to display message,
3. let me introduce something :innocent: 

I'm unsure we can do something like this, but:
- we can override `select` background (however it loses its `appearance`),
- we can use SVG inlined as data URI as `background-image`,
- we can use `<text>` SVG tag.

So [here's the idea implemented in CodePen](https://codepen.io/ffoodd/pen/abmjvGV). This has major drawbacks, though: 
1. it'll break `select` look & feel,
2. it might break layout as well: we need to check what happens in several types of form layouts (inlined, vertically stacked, etc.) and try to contain the overflow in some way (maybe properties like `contain` or `isolation` might help),
3. it requires to use string lentgh.

If we give this a shot, it'll need a brand new, dedicated mixin for such cases. And might be extended to other replaced and void elements (needs to deep dive onto testing).

@Dionakra As a first-step and to contribute to a kind of minimum viable test, you may add `select[required]:not([multiple])` as an advice with `$self-closing: true`. This is already a big step since it'd need documentation, and adding its message key to translation files. If so, I may move the inline SVG way of displaying message as another issue.

**Comment by Dionakra** [comment]
Great, I will do that, thanks!
